name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: get pharo 90 image
        run: | 
          curl get.pharo.org/64/90 | bash
          ls -R

      - name: get pharo 68021 (pharo 7.0)
        run: | 
          wget https://files.pharo.org/get-files/70/pharo64-linux-stable.zip
          unzip pharo64-linux-stable.zip
          ls -R

      - name: image version determination
        run: ./pharo --nodisplay Pharo.image --no-default-preferences eval '1 + 1'

